version: "3.7"

services:
  web:
    image: nginx:1.21
    # image → DockerHub から指定
    container_name: web
    ports:
      - "8080:80"
    volumes:
      - ./forDocker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/app/public
      # マウント
    depends_on:
      - app
      # コンテナが起動する順番を指定

  app:
    container_name: app
    build: .
    # build → Dockerfile のパスを指定（相対パス）
    tty: true
    # コンテナに疑似TTYを割り当てる
    # コンテナ側に仮想端末を置いて実行しているプロセスを用意してあげることによってコンテナを持続させることができる。
    stdin_open: true
    # コンテナの標準入力をオープンしたままにする
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./forDocker/mysql/conf.d:/etc/mysql/conf.d
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "docker-nginx-rails-mysql_development"
      TZ: "Asia/Tokyo"

volumes:
  dbdata:
  bundle:
